name: Convert notebooks

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  convert:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: |
          pip install nbconvert black numpy perfplot
          pip install .
      - name: Run black, notebooks and nbconvert
        run: |
          .github/workflows/traverse.sh .
      - name: Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          git add .
          git commit -m "upload generated files"
          git push
